//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeUserRole
    {
        public int user_role_id { get; set; }
        public string username { get; set; }
        public string role { get; set; }
    }
}
