//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeProduct
    {
        public int product_id { get; set; }
        public string product_code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string SKU { get; set; }
        public string SKU2 { get; set; }
        public Nullable<decimal> buy_price { get; set; }
        public Nullable<decimal> sell_price { get; set; }
        public Nullable<int> product_brand_id { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public Nullable<int> product_variety_id { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
