//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbShopeeAutomationV2Entities : DbContext
    {
        public dbShopeeAutomationV2Entities()
            : base("name=dbShopeeAutomationV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TShopeeCarrier> TShopeeCarriers { get; set; }
        public virtual DbSet<TShopeeCustomer> TShopeeCustomers { get; set; }
        public virtual DbSet<TShopeeDetail> TShopeeDetails { get; set; }
        public virtual DbSet<TShopeeOrderItem> TShopeeOrderItems { get; set; }
        public virtual DbSet<TShopeeOrderStatu> TShopeeOrderStatus { get; set; }
        public virtual DbSet<TShopeePaymentMethod> TShopeePaymentMethods { get; set; }
        public virtual DbSet<TShopeePlatform> TShopeePlatforms { get; set; }
        public virtual DbSet<TShopeeProductBrand> TShopeeProductBrands { get; set; }
        public virtual DbSet<TShopeeProductionDetail> TShopeeProductionDetails { get; set; }
        public virtual DbSet<TShopeeProductType> TShopeeProductTypes { get; set; }
        public virtual DbSet<TShopeeProductVariety> TShopeeProductVarieties { get; set; }
        public virtual DbSet<TShopeeShipmentStatu> TShopeeShipmentStatus { get; set; }
        public virtual DbSet<TShopeeStockItem> TShopeeStockItems { get; set; }
        public virtual DbSet<TShopeeStockWarehouse> TShopeeStockWarehouses { get; set; }
        public virtual DbSet<TShopeeUser> TShopeeUsers { get; set; }
        public virtual DbSet<TShopeeUserRole> TShopeeUserRoles { get; set; }
        public virtual DbSet<TShopeeProduct> TShopeeProducts { get; set; }
        public virtual DbSet<TShopeeInvoiceStatu> TShopeeInvoiceStatus { get; set; }
        public virtual DbSet<TShopeeOrder> TShopeeOrders { get; set; }
        public virtual DbSet<TShopeeOrderItemStatu> TShopeeOrderItemStatus { get; set; }
        public virtual DbSet<TShopeeInvoice> TShopeeInvoices { get; set; }
        public virtual DbSet<TShopeeShipment> TShopeeShipments { get; set; }
        public virtual DbSet<TShopeeProduction> TShopeeProductions { get; set; }
        public virtual DbSet<TShopeeProductionStatu> TShopeeProductionStatus { get; set; }
    
        public virtual int NSP_TShopeeCarrier_Delete(Nullable<int> carrier_id)
        {
            var carrier_idParameter = carrier_id.HasValue ?
                new ObjectParameter("carrier_id", carrier_id) :
                new ObjectParameter("carrier_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCarrier_Delete", carrier_idParameter);
        }
    
        public virtual int NSP_TShopeeCarrier_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCarrier_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeCarrier_Update(Nullable<int> carrier_id, string name, Nullable<int> detail_id)
        {
            var carrier_idParameter = carrier_id.HasValue ?
                new ObjectParameter("carrier_id", carrier_id) :
                new ObjectParameter("carrier_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCarrier_Update", carrier_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeCustomer_Delete(Nullable<int> customer_id)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCustomer_Delete", customer_idParameter);
        }
    
        public virtual int NSP_TShopeeCustomer_Insert(string first_name, string last_name, Nullable<System.DateTime> dob, string email_address, string phone_number, string address_line_1, string address_line_2, string city, string state, Nullable<int> zip_code, string country, Nullable<int> platform_id, Nullable<int> detail_id)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var address_line_1Parameter = address_line_1 != null ?
                new ObjectParameter("address_line_1", address_line_1) :
                new ObjectParameter("address_line_1", typeof(string));
    
            var address_line_2Parameter = address_line_2 != null ?
                new ObjectParameter("address_line_2", address_line_2) :
                new ObjectParameter("address_line_2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zip_codeParameter = zip_code.HasValue ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCustomer_Insert", first_nameParameter, last_nameParameter, dobParameter, email_addressParameter, phone_numberParameter, address_line_1Parameter, address_line_2Parameter, cityParameter, stateParameter, zip_codeParameter, countryParameter, platform_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeCustomer_Update(Nullable<int> customer_id, string first_name, string last_name, Nullable<System.DateTime> dob, string email_address, string phone_number, string address_line_1, string address_line_2, string city, string state, Nullable<int> zip_code, string country, Nullable<int> platform_id, Nullable<int> detail_id)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var address_line_1Parameter = address_line_1 != null ?
                new ObjectParameter("address_line_1", address_line_1) :
                new ObjectParameter("address_line_1", typeof(string));
    
            var address_line_2Parameter = address_line_2 != null ?
                new ObjectParameter("address_line_2", address_line_2) :
                new ObjectParameter("address_line_2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zip_codeParameter = zip_code.HasValue ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCustomer_Update", customer_idParameter, first_nameParameter, last_nameParameter, dobParameter, email_addressParameter, phone_numberParameter, address_line_1Parameter, address_line_2Parameter, cityParameter, stateParameter, zip_codeParameter, countryParameter, platform_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeDetail_Delete(Nullable<int> detail_id)
        {
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeDetail_Delete", detail_idParameter);
        }
    
        public virtual int NSP_TShopeeDetail_Insert(string status, string remark, string created_by, Nullable<System.DateTime> created_date, string last_updated_by, Nullable<System.DateTime> last_updated_date)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var last_updated_byParameter = last_updated_by != null ?
                new ObjectParameter("last_updated_by", last_updated_by) :
                new ObjectParameter("last_updated_by", typeof(string));
    
            var last_updated_dateParameter = last_updated_date.HasValue ?
                new ObjectParameter("last_updated_date", last_updated_date) :
                new ObjectParameter("last_updated_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeDetail_Insert", statusParameter, remarkParameter, created_byParameter, created_dateParameter, last_updated_byParameter, last_updated_dateParameter);
        }
    
        public virtual int NSP_TShopeeDetail_Update(Nullable<int> detail_id, string status, string remark, string created_by, Nullable<System.DateTime> created_date, string last_updated_by, Nullable<System.DateTime> last_updated_date)
        {
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var last_updated_byParameter = last_updated_by != null ?
                new ObjectParameter("last_updated_by", last_updated_by) :
                new ObjectParameter("last_updated_by", typeof(string));
    
            var last_updated_dateParameter = last_updated_date.HasValue ?
                new ObjectParameter("last_updated_date", last_updated_date) :
                new ObjectParameter("last_updated_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeDetail_Update", detail_idParameter, statusParameter, remarkParameter, created_byParameter, created_dateParameter, last_updated_byParameter, last_updated_dateParameter);
        }
    
        public virtual int NSP_TShopeeOrderItem_Delete(Nullable<int> order_item_id)
        {
            var order_item_idParameter = order_item_id.HasValue ?
                new ObjectParameter("order_item_id", order_item_id) :
                new ObjectParameter("order_item_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItem_Delete", order_item_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItem_Insert(Nullable<int> quantity, Nullable<decimal> sub_total, Nullable<decimal> discount_fee, Nullable<int> rMA_num, string rMA_issued_by, Nullable<System.DateTime> rMA_issued_date, Nullable<int> order_id, Nullable<int> order_item_status_id, Nullable<int> product_id, Nullable<int> detail_id)
        {
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var sub_totalParameter = sub_total.HasValue ?
                new ObjectParameter("sub_total", sub_total) :
                new ObjectParameter("sub_total", typeof(decimal));
    
            var discount_feeParameter = discount_fee.HasValue ?
                new ObjectParameter("discount_fee", discount_fee) :
                new ObjectParameter("discount_fee", typeof(decimal));
    
            var rMA_numParameter = rMA_num.HasValue ?
                new ObjectParameter("RMA_num", rMA_num) :
                new ObjectParameter("RMA_num", typeof(int));
    
            var rMA_issued_byParameter = rMA_issued_by != null ?
                new ObjectParameter("RMA_issued_by", rMA_issued_by) :
                new ObjectParameter("RMA_issued_by", typeof(string));
    
            var rMA_issued_dateParameter = rMA_issued_date.HasValue ?
                new ObjectParameter("RMA_issued_date", rMA_issued_date) :
                new ObjectParameter("RMA_issued_date", typeof(System.DateTime));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItem_Insert", quantityParameter, sub_totalParameter, discount_feeParameter, rMA_numParameter, rMA_issued_byParameter, rMA_issued_dateParameter, order_idParameter, order_item_status_idParameter, product_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItem_Update(Nullable<int> order_item_id, Nullable<int> quantity, Nullable<decimal> sub_total, Nullable<decimal> discount_fee, Nullable<int> rMA_num, string rMA_issued_by, Nullable<System.DateTime> rMA_issued_date, Nullable<int> order_id, Nullable<int> order_item_status_id, Nullable<int> product_id, Nullable<int> detail_id)
        {
            var order_item_idParameter = order_item_id.HasValue ?
                new ObjectParameter("order_item_id", order_item_id) :
                new ObjectParameter("order_item_id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var sub_totalParameter = sub_total.HasValue ?
                new ObjectParameter("sub_total", sub_total) :
                new ObjectParameter("sub_total", typeof(decimal));
    
            var discount_feeParameter = discount_fee.HasValue ?
                new ObjectParameter("discount_fee", discount_fee) :
                new ObjectParameter("discount_fee", typeof(decimal));
    
            var rMA_numParameter = rMA_num.HasValue ?
                new ObjectParameter("RMA_num", rMA_num) :
                new ObjectParameter("RMA_num", typeof(int));
    
            var rMA_issued_byParameter = rMA_issued_by != null ?
                new ObjectParameter("RMA_issued_by", rMA_issued_by) :
                new ObjectParameter("RMA_issued_by", typeof(string));
    
            var rMA_issued_dateParameter = rMA_issued_date.HasValue ?
                new ObjectParameter("RMA_issued_date", rMA_issued_date) :
                new ObjectParameter("RMA_issued_date", typeof(System.DateTime));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItem_Update", order_item_idParameter, quantityParameter, sub_totalParameter, discount_feeParameter, rMA_numParameter, rMA_issued_byParameter, rMA_issued_dateParameter, order_idParameter, order_item_status_idParameter, product_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderStatus_Delete(Nullable<int> order_status_id)
        {
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderStatus_Delete", order_status_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderStatus_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderStatus_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderStatus_Update(Nullable<int> order_status_id, string name, Nullable<int> detail_id)
        {
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderStatus_Update", order_status_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeePaymentMethod_Delete(Nullable<int> payment_method_id)
        {
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePaymentMethod_Delete", payment_method_idParameter);
        }
    
        public virtual int NSP_TShopeePaymentMethod_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePaymentMethod_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeePaymentMethod_Update(Nullable<int> payment_method_id, string name, Nullable<int> detail_id)
        {
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePaymentMethod_Update", payment_method_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeePlatform_Delete(Nullable<int> platform_id)
        {
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePlatform_Delete", platform_idParameter);
        }
    
        public virtual int NSP_TShopeePlatform_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePlatform_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeePlatform_Update(Nullable<int> platform_id, string name, Nullable<int> detail_id)
        {
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePlatform_Update", platform_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductBrand_Delete(Nullable<int> product_brand_id)
        {
            var product_brand_idParameter = product_brand_id.HasValue ?
                new ObjectParameter("product_brand_id", product_brand_id) :
                new ObjectParameter("product_brand_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductBrand_Delete", product_brand_idParameter);
        }
    
        public virtual int NSP_TShopeeProductBrand_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductBrand_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductBrand_Update(Nullable<int> product_brand_id, string name, Nullable<int> detail_id)
        {
            var product_brand_idParameter = product_brand_id.HasValue ?
                new ObjectParameter("product_brand_id", product_brand_id) :
                new ObjectParameter("product_brand_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductBrand_Update", product_brand_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductionDetail_Delete(Nullable<int> production_detail_id)
        {
            var production_detail_idParameter = production_detail_id.HasValue ?
                new ObjectParameter("production_detail_id", production_detail_id) :
                new ObjectParameter("production_detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductionDetail_Delete", production_detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductionDetail_Insert(string uOM, Nullable<System.DateTime> manufactured_date, Nullable<System.DateTime> expiry_date, Nullable<int> quantity, Nullable<int> production_id, Nullable<int> product_id, Nullable<int> detail_id)
        {
            var uOMParameter = uOM != null ?
                new ObjectParameter("UOM", uOM) :
                new ObjectParameter("UOM", typeof(string));
    
            var manufactured_dateParameter = manufactured_date.HasValue ?
                new ObjectParameter("manufactured_date", manufactured_date) :
                new ObjectParameter("manufactured_date", typeof(System.DateTime));
    
            var expiry_dateParameter = expiry_date.HasValue ?
                new ObjectParameter("expiry_date", expiry_date) :
                new ObjectParameter("expiry_date", typeof(System.DateTime));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var production_idParameter = production_id.HasValue ?
                new ObjectParameter("production_id", production_id) :
                new ObjectParameter("production_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductionDetail_Insert", uOMParameter, manufactured_dateParameter, expiry_dateParameter, quantityParameter, production_idParameter, product_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductionDetail_Update(Nullable<int> production_detail_id, string uOM, Nullable<System.DateTime> manufactured_date, Nullable<System.DateTime> expiry_date, Nullable<int> quantity, Nullable<int> production_id, Nullable<int> product_id, Nullable<int> detail_id)
        {
            var production_detail_idParameter = production_detail_id.HasValue ?
                new ObjectParameter("production_detail_id", production_detail_id) :
                new ObjectParameter("production_detail_id", typeof(int));
    
            var uOMParameter = uOM != null ?
                new ObjectParameter("UOM", uOM) :
                new ObjectParameter("UOM", typeof(string));
    
            var manufactured_dateParameter = manufactured_date.HasValue ?
                new ObjectParameter("manufactured_date", manufactured_date) :
                new ObjectParameter("manufactured_date", typeof(System.DateTime));
    
            var expiry_dateParameter = expiry_date.HasValue ?
                new ObjectParameter("expiry_date", expiry_date) :
                new ObjectParameter("expiry_date", typeof(System.DateTime));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var production_idParameter = production_id.HasValue ?
                new ObjectParameter("production_id", production_id) :
                new ObjectParameter("production_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductionDetail_Update", production_detail_idParameter, uOMParameter, manufactured_dateParameter, expiry_dateParameter, quantityParameter, production_idParameter, product_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductType_Delete(Nullable<int> product_type_id)
        {
            var product_type_idParameter = product_type_id.HasValue ?
                new ObjectParameter("product_type_id", product_type_id) :
                new ObjectParameter("product_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductType_Delete", product_type_idParameter);
        }
    
        public virtual int NSP_TShopeeProductType_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductType_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductType_Update(Nullable<int> product_type_id, string name, Nullable<int> detail_id)
        {
            var product_type_idParameter = product_type_id.HasValue ?
                new ObjectParameter("product_type_id", product_type_id) :
                new ObjectParameter("product_type_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductType_Update", product_type_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductVariety_Delete(Nullable<int> product_variety_id)
        {
            var product_variety_idParameter = product_variety_id.HasValue ?
                new ObjectParameter("product_variety_id", product_variety_id) :
                new ObjectParameter("product_variety_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductVariety_Delete", product_variety_idParameter);
        }
    
        public virtual int NSP_TShopeeProductVariety_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductVariety_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductVariety_Update(Nullable<int> product_variety_id, string name, Nullable<int> detail_id)
        {
            var product_variety_idParameter = product_variety_id.HasValue ?
                new ObjectParameter("product_variety_id", product_variety_id) :
                new ObjectParameter("product_variety_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductVariety_Update", product_variety_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeShipmentStatus_Delete(Nullable<int> shipment_status_id)
        {
            var shipment_status_idParameter = shipment_status_id.HasValue ?
                new ObjectParameter("shipment_status_id", shipment_status_id) :
                new ObjectParameter("shipment_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeShipmentStatus_Delete", shipment_status_idParameter);
        }
    
        public virtual int NSP_TShopeeShipmentStatus_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeShipmentStatus_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeShipmentStatus_Update(Nullable<int> shipment_status_id, string name, Nullable<int> detail_id)
        {
            var shipment_status_idParameter = shipment_status_id.HasValue ?
                new ObjectParameter("shipment_status_id", shipment_status_id) :
                new ObjectParameter("shipment_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeShipmentStatus_Update", shipment_status_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeStockItem_Delete(Nullable<int> stock_item_id)
        {
            var stock_item_idParameter = stock_item_id.HasValue ?
                new ObjectParameter("stock_item_id", stock_item_id) :
                new ObjectParameter("stock_item_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeStockItem_Delete", stock_item_idParameter);
        }
    
        public virtual int NSP_TShopeeStockItem_Insert(string name, string description, Nullable<int> stock_quantity, Nullable<int> product_id, Nullable<int> stock_warehouse_id, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var stock_quantityParameter = stock_quantity.HasValue ?
                new ObjectParameter("stock_quantity", stock_quantity) :
                new ObjectParameter("stock_quantity", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var stock_warehouse_idParameter = stock_warehouse_id.HasValue ?
                new ObjectParameter("stock_warehouse_id", stock_warehouse_id) :
                new ObjectParameter("stock_warehouse_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeStockItem_Insert", nameParameter, descriptionParameter, stock_quantityParameter, product_idParameter, stock_warehouse_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeStockItem_Update(Nullable<int> stock_item_id, string name, string description, Nullable<int> stock_quantity, Nullable<int> product_id, Nullable<int> stock_warehouse_id, Nullable<int> detail_id)
        {
            var stock_item_idParameter = stock_item_id.HasValue ?
                new ObjectParameter("stock_item_id", stock_item_id) :
                new ObjectParameter("stock_item_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var stock_quantityParameter = stock_quantity.HasValue ?
                new ObjectParameter("stock_quantity", stock_quantity) :
                new ObjectParameter("stock_quantity", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var stock_warehouse_idParameter = stock_warehouse_id.HasValue ?
                new ObjectParameter("stock_warehouse_id", stock_warehouse_id) :
                new ObjectParameter("stock_warehouse_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeStockItem_Update", stock_item_idParameter, nameParameter, descriptionParameter, stock_quantityParameter, product_idParameter, stock_warehouse_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeStockWarehouse_Delete(Nullable<int> stock_warehouse_id)
        {
            var stock_warehouse_idParameter = stock_warehouse_id.HasValue ?
                new ObjectParameter("stock_warehouse_id", stock_warehouse_id) :
                new ObjectParameter("stock_warehouse_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeStockWarehouse_Delete", stock_warehouse_idParameter);
        }
    
        public virtual int NSP_TShopeeStockWarehouse_Insert(string name, string email_address, string phone_number, string address_line_1, string address_line_2, string city, string state, Nullable<int> zip_code, string country, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var address_line_1Parameter = address_line_1 != null ?
                new ObjectParameter("address_line_1", address_line_1) :
                new ObjectParameter("address_line_1", typeof(string));
    
            var address_line_2Parameter = address_line_2 != null ?
                new ObjectParameter("address_line_2", address_line_2) :
                new ObjectParameter("address_line_2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zip_codeParameter = zip_code.HasValue ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeStockWarehouse_Insert", nameParameter, email_addressParameter, phone_numberParameter, address_line_1Parameter, address_line_2Parameter, cityParameter, stateParameter, zip_codeParameter, countryParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeStockWarehouse_Update(Nullable<int> stock_warehouse_id, string name, string email_address, string phone_number, string address_line_1, string address_line_2, string city, string state, Nullable<int> zip_code, string country, Nullable<int> detail_id)
        {
            var stock_warehouse_idParameter = stock_warehouse_id.HasValue ?
                new ObjectParameter("stock_warehouse_id", stock_warehouse_id) :
                new ObjectParameter("stock_warehouse_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var address_line_1Parameter = address_line_1 != null ?
                new ObjectParameter("address_line_1", address_line_1) :
                new ObjectParameter("address_line_1", typeof(string));
    
            var address_line_2Parameter = address_line_2 != null ?
                new ObjectParameter("address_line_2", address_line_2) :
                new ObjectParameter("address_line_2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zip_codeParameter = zip_code.HasValue ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeStockWarehouse_Update", stock_warehouse_idParameter, nameParameter, email_addressParameter, phone_numberParameter, address_line_1Parameter, address_line_2Parameter, cityParameter, stateParameter, zip_codeParameter, countryParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeUser_Delete(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeUser_Delete", user_idParameter);
        }
    
        public virtual int NSP_TShopeeUser_Insert(string username, string password, string email)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeUser_Insert", usernameParameter, passwordParameter, emailParameter);
        }
    
        public virtual int NSP_TShopeeUser_Update(Nullable<int> user_id, string username, string password, string email)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeUser_Update", user_idParameter, usernameParameter, passwordParameter, emailParameter);
        }
    
        public virtual int NSP_TShopeeUserRole_Delete(Nullable<int> user_role_id)
        {
            var user_role_idParameter = user_role_id.HasValue ?
                new ObjectParameter("user_role_id", user_role_id) :
                new ObjectParameter("user_role_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeUserRole_Delete", user_role_idParameter);
        }
    
        public virtual int NSP_TShopeeUserRole_Insert(string username, string role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeUserRole_Insert", usernameParameter, roleParameter);
        }
    
        public virtual int NSP_TShopeeUserRole_Update(Nullable<int> user_role_id, string username, string role)
        {
            var user_role_idParameter = user_role_id.HasValue ?
                new ObjectParameter("user_role_id", user_role_id) :
                new ObjectParameter("user_role_id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeUserRole_Update", user_role_idParameter, usernameParameter, roleParameter);
        }
    
        public virtual int NSP_TShopeeProduct_Delete(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProduct_Delete", product_idParameter);
        }
    
        public virtual int NSP_TShopeeProduct_Insert(string product_code, string name, string description, string sKU, string sKU2, Nullable<decimal> buy_price, Nullable<decimal> sell_price, Nullable<int> product_brand_id, Nullable<int> product_type_id, Nullable<int> product_variety_id, Nullable<int> detail_id)
        {
            var product_codeParameter = product_code != null ?
                new ObjectParameter("product_code", product_code) :
                new ObjectParameter("product_code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var sKU2Parameter = sKU2 != null ?
                new ObjectParameter("SKU2", sKU2) :
                new ObjectParameter("SKU2", typeof(string));
    
            var buy_priceParameter = buy_price.HasValue ?
                new ObjectParameter("buy_price", buy_price) :
                new ObjectParameter("buy_price", typeof(decimal));
    
            var sell_priceParameter = sell_price.HasValue ?
                new ObjectParameter("sell_price", sell_price) :
                new ObjectParameter("sell_price", typeof(decimal));
    
            var product_brand_idParameter = product_brand_id.HasValue ?
                new ObjectParameter("product_brand_id", product_brand_id) :
                new ObjectParameter("product_brand_id", typeof(int));
    
            var product_type_idParameter = product_type_id.HasValue ?
                new ObjectParameter("product_type_id", product_type_id) :
                new ObjectParameter("product_type_id", typeof(int));
    
            var product_variety_idParameter = product_variety_id.HasValue ?
                new ObjectParameter("product_variety_id", product_variety_id) :
                new ObjectParameter("product_variety_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProduct_Insert", product_codeParameter, nameParameter, descriptionParameter, sKUParameter, sKU2Parameter, buy_priceParameter, sell_priceParameter, product_brand_idParameter, product_type_idParameter, product_variety_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProduct_Update(Nullable<int> product_id, string product_code, string name, string description, string sKU, string sKU2, Nullable<decimal> buy_price, Nullable<decimal> sell_price, Nullable<int> product_brand_id, Nullable<int> product_type_id, Nullable<int> product_variety_id, Nullable<int> detail_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var product_codeParameter = product_code != null ?
                new ObjectParameter("product_code", product_code) :
                new ObjectParameter("product_code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var sKUParameter = sKU != null ?
                new ObjectParameter("SKU", sKU) :
                new ObjectParameter("SKU", typeof(string));
    
            var sKU2Parameter = sKU2 != null ?
                new ObjectParameter("SKU2", sKU2) :
                new ObjectParameter("SKU2", typeof(string));
    
            var buy_priceParameter = buy_price.HasValue ?
                new ObjectParameter("buy_price", buy_price) :
                new ObjectParameter("buy_price", typeof(decimal));
    
            var sell_priceParameter = sell_price.HasValue ?
                new ObjectParameter("sell_price", sell_price) :
                new ObjectParameter("sell_price", typeof(decimal));
    
            var product_brand_idParameter = product_brand_id.HasValue ?
                new ObjectParameter("product_brand_id", product_brand_id) :
                new ObjectParameter("product_brand_id", typeof(int));
    
            var product_type_idParameter = product_type_id.HasValue ?
                new ObjectParameter("product_type_id", product_type_id) :
                new ObjectParameter("product_type_id", typeof(int));
    
            var product_variety_idParameter = product_variety_id.HasValue ?
                new ObjectParameter("product_variety_id", product_variety_id) :
                new ObjectParameter("product_variety_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProduct_Update", product_idParameter, product_codeParameter, nameParameter, descriptionParameter, sKUParameter, sKU2Parameter, buy_priceParameter, sell_priceParameter, product_brand_idParameter, product_type_idParameter, product_variety_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoiceStatus_Delete(Nullable<int> invoice_status_id)
        {
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoiceStatus_Delete", invoice_status_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoiceStatus_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoiceStatus_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoiceStatus_Update(Nullable<int> invoice_status_id, string name, Nullable<int> detail_id)
        {
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoiceStatus_Update", invoice_status_idParameter, nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrder_Delete(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrder_Delete", order_idParameter);
        }
    
        public virtual int NSP_TShopeeOrder_Insert(string order_title, Nullable<System.DateTime> order_placed_date, Nullable<decimal> total_price, Nullable<int> order_status_id, Nullable<int> detail_id)
        {
            var order_titleParameter = order_title != null ?
                new ObjectParameter("order_title", order_title) :
                new ObjectParameter("order_title", typeof(string));
    
            var order_placed_dateParameter = order_placed_date.HasValue ?
                new ObjectParameter("order_placed_date", order_placed_date) :
                new ObjectParameter("order_placed_date", typeof(System.DateTime));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrder_Insert", order_titleParameter, order_placed_dateParameter, total_priceParameter, order_status_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrder_Update(Nullable<int> order_id, string order_title, Nullable<System.DateTime> order_placed_date, Nullable<decimal> total_price, Nullable<int> order_status_id, Nullable<int> detail_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var order_titleParameter = order_title != null ?
                new ObjectParameter("order_title", order_title) :
                new ObjectParameter("order_title", typeof(string));
    
            var order_placed_dateParameter = order_placed_date.HasValue ?
                new ObjectParameter("order_placed_date", order_placed_date) :
                new ObjectParameter("order_placed_date", typeof(System.DateTime));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrder_Update", order_idParameter, order_titleParameter, order_placed_dateParameter, total_priceParameter, order_status_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItemStatus_Delete(Nullable<int> order_item_status_id)
        {
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItemStatus_Delete", order_item_status_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItemStatus_Insert(string name, string description, Nullable<int> return_merchandise_authorization_nr, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var return_merchandise_authorization_nrParameter = return_merchandise_authorization_nr.HasValue ?
                new ObjectParameter("return_merchandise_authorization_nr", return_merchandise_authorization_nr) :
                new ObjectParameter("return_merchandise_authorization_nr", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItemStatus_Insert", nameParameter, descriptionParameter, return_merchandise_authorization_nrParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItemStatus_Update(Nullable<int> order_item_status_id, string name, string description, Nullable<int> return_merchandise_authorization_nr, Nullable<int> detail_id)
        {
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var return_merchandise_authorization_nrParameter = return_merchandise_authorization_nr.HasValue ?
                new ObjectParameter("return_merchandise_authorization_nr", return_merchandise_authorization_nr) :
                new ObjectParameter("return_merchandise_authorization_nr", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItemStatus_Update", order_item_status_idParameter, nameParameter, descriptionParameter, return_merchandise_authorization_nrParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoice_Delete(Nullable<int> invoice_id)
        {
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoice_Delete", invoice_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoice_Insert(string invoice_title, Nullable<System.DateTime> invoice_date, string invoice_details, Nullable<decimal> shipping_fee, Nullable<int> invoice_status_id, Nullable<int> payment_method_id, Nullable<int> order_id, Nullable<int> customer_id, Nullable<int> detail_id)
        {
            var invoice_titleParameter = invoice_title != null ?
                new ObjectParameter("invoice_title", invoice_title) :
                new ObjectParameter("invoice_title", typeof(string));
    
            var invoice_dateParameter = invoice_date.HasValue ?
                new ObjectParameter("invoice_date", invoice_date) :
                new ObjectParameter("invoice_date", typeof(System.DateTime));
    
            var invoice_detailsParameter = invoice_details != null ?
                new ObjectParameter("invoice_details", invoice_details) :
                new ObjectParameter("invoice_details", typeof(string));
    
            var shipping_feeParameter = shipping_fee.HasValue ?
                new ObjectParameter("shipping_fee", shipping_fee) :
                new ObjectParameter("shipping_fee", typeof(decimal));
    
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoice_Insert", invoice_titleParameter, invoice_dateParameter, invoice_detailsParameter, shipping_feeParameter, invoice_status_idParameter, payment_method_idParameter, order_idParameter, customer_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoice_Update(Nullable<int> invoice_id, string invoice_title, Nullable<System.DateTime> invoice_date, string invoice_details, Nullable<decimal> shipping_fee, Nullable<int> invoice_status_id, Nullable<int> payment_method_id, Nullable<int> order_id, Nullable<int> customer_id, Nullable<int> detail_id)
        {
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            var invoice_titleParameter = invoice_title != null ?
                new ObjectParameter("invoice_title", invoice_title) :
                new ObjectParameter("invoice_title", typeof(string));
    
            var invoice_dateParameter = invoice_date.HasValue ?
                new ObjectParameter("invoice_date", invoice_date) :
                new ObjectParameter("invoice_date", typeof(System.DateTime));
    
            var invoice_detailsParameter = invoice_details != null ?
                new ObjectParameter("invoice_details", invoice_details) :
                new ObjectParameter("invoice_details", typeof(string));
    
            var shipping_feeParameter = shipping_fee.HasValue ?
                new ObjectParameter("shipping_fee", shipping_fee) :
                new ObjectParameter("shipping_fee", typeof(decimal));
    
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoice_Update", invoice_idParameter, invoice_titleParameter, invoice_dateParameter, invoice_detailsParameter, shipping_feeParameter, invoice_status_idParameter, payment_method_idParameter, order_idParameter, customer_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeShipment_Delete(Nullable<int> shipment_id)
        {
            var shipment_idParameter = shipment_id.HasValue ?
                new ObjectParameter("shipment_id", shipment_id) :
                new ObjectParameter("shipment_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeShipment_Delete", shipment_idParameter);
        }
    
        public virtual int NSP_TShopeeShipment_Insert(string start_location, string destination, string tracking_id, Nullable<System.DateTime> created_date, Nullable<System.DateTime> expected_date, Nullable<System.DateTime> due_date, Nullable<int> invoice_id, Nullable<int> carrier_id, Nullable<int> shipment_status_id, Nullable<int> detail_id)
        {
            var start_locationParameter = start_location != null ?
                new ObjectParameter("start_location", start_location) :
                new ObjectParameter("start_location", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("destination", destination) :
                new ObjectParameter("destination", typeof(string));
    
            var tracking_idParameter = tracking_id != null ?
                new ObjectParameter("tracking_id", tracking_id) :
                new ObjectParameter("tracking_id", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var expected_dateParameter = expected_date.HasValue ?
                new ObjectParameter("expected_date", expected_date) :
                new ObjectParameter("expected_date", typeof(System.DateTime));
    
            var due_dateParameter = due_date.HasValue ?
                new ObjectParameter("due_date", due_date) :
                new ObjectParameter("due_date", typeof(System.DateTime));
    
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            var carrier_idParameter = carrier_id.HasValue ?
                new ObjectParameter("carrier_id", carrier_id) :
                new ObjectParameter("carrier_id", typeof(int));
    
            var shipment_status_idParameter = shipment_status_id.HasValue ?
                new ObjectParameter("shipment_status_id", shipment_status_id) :
                new ObjectParameter("shipment_status_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeShipment_Insert", start_locationParameter, destinationParameter, tracking_idParameter, created_dateParameter, expected_dateParameter, due_dateParameter, invoice_idParameter, carrier_idParameter, shipment_status_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeShipment_Update(Nullable<int> shipment_id, string start_location, string destination, string tracking_id, Nullable<System.DateTime> created_date, Nullable<System.DateTime> expected_date, Nullable<System.DateTime> due_date, Nullable<int> invoice_id, Nullable<int> carrier_id, Nullable<int> shipment_status_id, Nullable<int> detail_id)
        {
            var shipment_idParameter = shipment_id.HasValue ?
                new ObjectParameter("shipment_id", shipment_id) :
                new ObjectParameter("shipment_id", typeof(int));
    
            var start_locationParameter = start_location != null ?
                new ObjectParameter("start_location", start_location) :
                new ObjectParameter("start_location", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("destination", destination) :
                new ObjectParameter("destination", typeof(string));
    
            var tracking_idParameter = tracking_id != null ?
                new ObjectParameter("tracking_id", tracking_id) :
                new ObjectParameter("tracking_id", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var expected_dateParameter = expected_date.HasValue ?
                new ObjectParameter("expected_date", expected_date) :
                new ObjectParameter("expected_date", typeof(System.DateTime));
    
            var due_dateParameter = due_date.HasValue ?
                new ObjectParameter("due_date", due_date) :
                new ObjectParameter("due_date", typeof(System.DateTime));
    
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            var carrier_idParameter = carrier_id.HasValue ?
                new ObjectParameter("carrier_id", carrier_id) :
                new ObjectParameter("carrier_id", typeof(int));
    
            var shipment_status_idParameter = shipment_status_id.HasValue ?
                new ObjectParameter("shipment_status_id", shipment_status_id) :
                new ObjectParameter("shipment_status_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeShipment_Update", shipment_idParameter, start_locationParameter, destinationParameter, tracking_idParameter, created_dateParameter, expected_dateParameter, due_dateParameter, invoice_idParameter, carrier_idParameter, shipment_status_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProduction_Delete(Nullable<int> production_id)
        {
            var production_idParameter = production_id.HasValue ?
                new ObjectParameter("production_id", production_id) :
                new ObjectParameter("production_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProduction_Delete", production_idParameter);
        }
    
        public virtual int NSP_TShopeeProduction_Insert(string title, string description, Nullable<int> production_status_id, Nullable<int> detail_id)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var production_status_idParameter = production_status_id.HasValue ?
                new ObjectParameter("production_status_id", production_status_id) :
                new ObjectParameter("production_status_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProduction_Insert", titleParameter, descriptionParameter, production_status_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProduction_Update(Nullable<int> production_id, string title, string description, Nullable<int> production_status_id, Nullable<int> detail_id)
        {
            var production_idParameter = production_id.HasValue ?
                new ObjectParameter("production_id", production_id) :
                new ObjectParameter("production_id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var production_status_idParameter = production_status_id.HasValue ?
                new ObjectParameter("production_status_id", production_status_id) :
                new ObjectParameter("production_status_id", typeof(int));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProduction_Update", production_idParameter, titleParameter, descriptionParameter, production_status_idParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductionStatus_Delete(Nullable<int> production_status_id)
        {
            var production_status_idParameter = production_status_id.HasValue ?
                new ObjectParameter("production_status_id", production_status_id) :
                new ObjectParameter("production_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductionStatus_Delete", production_status_idParameter);
        }
    
        public virtual int NSP_TShopeeProductionStatus_Insert(string name, Nullable<int> detail_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductionStatus_Insert", nameParameter, detail_idParameter);
        }
    
        public virtual int NSP_TShopeeProductionStatus_Update(Nullable<int> production_status_id, string name, Nullable<int> detail_id)
        {
            var production_status_idParameter = production_status_id.HasValue ?
                new ObjectParameter("production_status_id", production_status_id) :
                new ObjectParameter("production_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var detail_idParameter = detail_id.HasValue ?
                new ObjectParameter("detail_id", detail_id) :
                new ObjectParameter("detail_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeProductionStatus_Update", production_status_idParameter, nameParameter, detail_idParameter);
        }
    }
}
