//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeProduction
    {
        public int production_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<int> detail_id { get; set; }

        public TShopeeProduction()
        {

        }

        public TShopeeProduction(int production_id)
        {
            this.production_id = production_id;
        }
    }
}
