//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeSupplierShipment
    {
        public int supplier_shipment_id { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string supplier_tracking_id { get; set; }
        public string NTL_tracking_id { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
