//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeProductBrand
    {
        public int product_brand_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
