//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeProductComponent
    {
        public int product_component_id { get; set; }
        public Nullable<int> master_product_id { get; set; }
        public Nullable<int> sub_product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
