//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeDetail
    {
        public int detail_id { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_updated_by { get; set; }
        public Nullable<System.DateTime> last_updated_date { get; set; }

        public TShopeeDetail()
        {

        }
    }
}
