//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeProductionDetail
    {
        public int production_detail_id { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> manufactured_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> production_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> detail_id { get; set; }
    }
}
