//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeAutomationV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeShipment
    {
        public int shipment_id { get; set; }
        public string start_location { get; set; }
        public string destination { get; set; }
        public string tracking_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> expected_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> carrier_id { get; set; }
        public string shipment_status { get; set; }
        public Nullable<int> detail_id { get; set; }

        public TShopeeShipment()
        {

        }
    }
}
